"""Central city/station configuration for NWS Rainfall Monitor.

The climate_product_id values point to the NWS Daily Climate Report product
family used for settlement-style monthly precipitation checks. The
observation_station values are the airport/official station IDs most useful
for local station context and future NOAA/NOWData integrations.
"""

CITIES = {
    "Atlanta": {
        "station_id": "CLIATL",
        "observation_station": "KATL",
        "wfo": "FFC",
        "location": "Atlanta, GA",
        "timezone": "America/New_York",
        "latitude": 33.6407,
        "longitude": -84.4277,
        "kalshi_market": "KXRAINATLM",
    },
    "Austin": {
        "station_id": "CLIAUS",
        "observation_station": "KAUS",
        "wfo": "EWX",
        "location": "Austin, TX",
        "timezone": "America/Chicago",
        "latitude": 30.1975,
        "longitude": -97.6664,
        "kalshi_market": "KXRAINAUSM",
    },
    "Boston": {
        "station_id": "CLIBOS",
        "observation_station": "KBOS",
        "wfo": "BOX",
        "location": "Boston, MA",
        "timezone": "America/New_York",
        "latitude": 42.3656,
        "longitude": -71.0096,
        "kalshi_market": "KXRAINBOSM",
    },
    "Chicago": {
        "station_id": "CLIORD",
        "observation_station": "KORD",
        "wfo": "LOT",
        "location": "Chicago O'Hare, IL",
        "timezone": "America/Chicago",
        "latitude": 41.9742,
        "longitude": -87.9073,
        "kalshi_market": "KXRAINCHIM",
    },
    "Dallas": {
        "station_id": "CLIDFW",
        "observation_station": "KDFW",
        "wfo": "FWD",
        "location": "Dallas-Fort Worth, TX",
        "timezone": "America/Chicago",
        "latitude": 32.8998,
        "longitude": -97.0403,
        "kalshi_market": "KXRAINDFWM",
    },
    "Denver": {
        "station_id": "CLIDEN",
        "observation_station": "KDEN",
        "wfo": "BOU",
        "location": "Denver, CO",
        "timezone": "America/Denver",
        "latitude": 39.8561,
        "longitude": -104.6737,
        "kalshi_market": "KXRAINDENM",
    },
    "Houston": {
        "station_id": "CLIIAH",
        "observation_station": "KIAH",
        "wfo": "HGX",
        "location": "Houston, TX",
        "timezone": "America/Chicago",
        "latitude": 29.9902,
        "longitude": -95.3368,
        "kalshi_market": "KXRAINHOUM",
    },
    "Las Vegas": {
        "station_id": "CLILAS",
        "observation_station": "KLAS",
        "wfo": "VEF",
        "location": "Las Vegas, NV",
        "timezone": "America/Los_Angeles",
        "latitude": 36.0840,
        "longitude": -115.1537,
        "kalshi_market": "KXRAINLASM",
    },
    "Los Angeles": {
        "station_id": "CLILAX",
        "observation_station": "KLAX",
        "wfo": "LOX",
        "location": "Los Angeles, CA",
        "timezone": "America/Los_Angeles",
        "latitude": 33.9416,
        "longitude": -118.4085,
        "kalshi_market": "KXRAINLAXM",
    },
    "Miami": {
        "station_id": "CLIMIA",
        "observation_station": "KMIA",
        "wfo": "MFL",
        "location": "Miami, FL",
        "timezone": "America/New_York",
        "latitude": 25.7959,
        "longitude": -80.2870,
        "kalshi_market": "KXRAINMIAM",
    },
    "Minneapolis": {
        "station_id": "CLIMSP",
        "observation_station": "KMSP",
        "wfo": "MPX",
        "location": "Minneapolis-St. Paul, MN",
        "timezone": "America/Chicago",
        "latitude": 44.8848,
        "longitude": -93.2223,
        "kalshi_market": "KXRAINMSPM",
    },
    "New Orleans": {
        "station_id": "CLIMSY",
        "observation_station": "KMSY",
        "wfo": "LIX",
        "location": "New Orleans, LA",
        "timezone": "America/Chicago",
        "latitude": 29.9934,
        "longitude": -90.2580,
        "kalshi_market": "KXRAINMSYM",
    },
    "New York City": {
        "station_id": "CLINYC",
        "observation_station": "KNYC",
        "wfo": "OKX",
        "location": "New York City, NY",
        "timezone": "America/New_York",
        "latitude": 40.7789,
        "longitude": -73.9692,
        "kalshi_market": "KXRAINNYCM",
    },
    "Oklahoma City": {
        "station_id": "CLIOKC",
        "observation_station": "KOKC",
        "wfo": "OUN",
        "location": "Oklahoma City, OK",
        "timezone": "America/Chicago",
        "latitude": 35.3931,
        "longitude": -97.6007,
        "kalshi_market": "KXRAINOKCM",
    },
    "Philadelphia": {
        "station_id": "CLIPHL",
        "observation_station": "KPHL",
        "wfo": "PHI",
        "location": "Philadelphia, PA",
        "timezone": "America/New_York",
        "latitude": 39.8744,
        "longitude": -75.2424,
        "kalshi_market": "KXRAINPHLM",
    },
    "Phoenix": {
        "station_id": "CLIPHX",
        "observation_station": "KPHX",
        "wfo": "PSR",
        "location": "Phoenix, AZ",
        "timezone": "America/Phoenix",
        "latitude": 33.4342,
        "longitude": -112.0116,
        "kalshi_market": "KXRAINPHXM",
    },
    "San Antonio": {
        "station_id": "CLISAT",
        "observation_station": "KSAT",
        "wfo": "EWX",
        "location": "San Antonio, TX",
        "timezone": "America/Chicago",
        "latitude": 29.5337,
        "longitude": -98.4698,
        "kalshi_market": "KXRAINSATM",
    },
    "San Francisco": {
        "station_id": "CLISFO",
        "observation_station": "KSFO",
        "wfo": "MTR",
        "location": "San Francisco, CA",
        "timezone": "America/Los_Angeles",
        "latitude": 37.6213,
        "longitude": -122.3790,
        "kalshi_market": "KXRAINSFOM",
    },
    "Seattle/Tacoma": {
        "station_id": "CLISEA",
        "observation_station": "KSEA",
        "wfo": "SEW",
        "location": "Seattle-Tacoma, WA",
        "timezone": "America/Los_Angeles",
        "latitude": 47.4502,
        "longitude": -122.3088,
        "kalshi_market": "KXRAINSEAM",
    },
    "Washington DC": {
        "station_id": "CLIDCA",
        "observation_station": "KDCA",
        "wfo": "LWX",
        "location": "Washington, DC",
        "timezone": "America/New_York",
        "latitude": 38.8512,
        "longitude": -77.0402,
        "kalshi_market": "KXRAINDCAM",
    },
}


def get_city_names():
    return list(CITIES.keys())


def get_city_config(city_name):
    return CITIES[city_name]
